#!/bin/bash
python setup.py bdist_egg
rm $HOME/tracproject/plugins/nonotif*
mv -f ./dist/* $HOME/tracproject/plugins/
killall tracstart
killall tracd &
echo 'starting tracd' && tracstart > $HOME/tracd_log &